#!/usr/bin/env bash

# Define  variables for file paths
NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
NGINX_DEFAULT_CONFIG="default"

# Check if Nginx is installed if not install Nginx
if ! command -v nginx &> /dev/null; then
	echo "Nginx is not installed. Installing Nginx.. Please Wait!"
	apt-get update
	apt-get install -y nginx
	echo "Installation Complete"
fi


# Check if the default configuration file exits
if [ ! -e "$NGINX_SITES_AVAILABLE/$NGINX_DEFAULT_CONFIG"]; then
	echo "Defult Nginx configuration file not found at $NGINX_SITE_AVAILABLE/$NGINX_DEFAULT_CONFIG"
	exit 1
fi

#create a symbolic link to the default configuration
ln -s "$NGINX_SITES_AVAILABLE/$NGINX_DEFAULT_CONFIG" "$NGINX_SITES_ENABLED/$NGINX_DEFAULT_CONFIG"

# Restart Nginx
service nginx restart

echo "NGINX configuration completed successfully."
