#!/usr/bin/env bash
#add file dir to program var


file="/etc/passwd"


#Check if the file exists
if [ -f "$file" ]; then
    # Read the file line by line using a while loop and IFS
    while IFS=: read -r username password uid gid gecos home shell; do
        # Extract additional information from the gecos field
        IFS=',' read -r user_info rest <<< "$gecos"

        # Display the required information in the specified format
        echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
        echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
        echo
    done < "$file"
else
    echo "File $file does not exist."
fi
