#!/usr/bin/env bash
# This script displays "Best School" 10 times with a special message on the 9th iteration.


i=0
while ((i < 10)); do
    if ((i == 8)); then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
