#!/usr/bin/env bash
#a script that displays numbers from 1 - 20 with set message at certain points


i=1
while ((i < 21)); do
	case $i in
        4)
		echo $i
		echo "bad luck from China"
		;;
        9)
		echo $i
		echo "bad luck from Japan"
		;;
        17)
		echo $i
		echo "bad luck from Italy"
		;;
        *)
		echo $i
		;;
    esac
    ((i++))
done 
